/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bg.jug.workshop.liferay.cfp.service;

import aQute.bnd.annotation.ProviderType;

import com.liferay.osgi.util.ServiceTrackerFactory;

import org.osgi.util.tracker.ServiceTracker;

/**
 * Provides the local service utility for Event. This utility wraps
 * {@link bg.jug.workshop.liferay.cfp.service.impl.EventLocalServiceImpl} and is the
 * primary access point for service operations in application layer code running
 * on the local server. Methods of this service will not have security checks
 * based on the propagated JAAS credentials because this service can only be
 * accessed from within the same VM.
 *
 * @author Brian Wing Shun Chan
 * @see EventLocalService
 * @see bg.jug.workshop.liferay.cfp.service.base.EventLocalServiceBaseImpl
 * @see bg.jug.workshop.liferay.cfp.service.impl.EventLocalServiceImpl
 * @generated
 */
@ProviderType
public class EventLocalServiceUtil {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify this class directly. Add custom service methods to {@link bg.jug.workshop.liferay.cfp.service.impl.EventLocalServiceImpl} and rerun ServiceBuilder to regenerate this class.
	 */

	/**
	* Adds the event to the database. Also notifies the appropriate model listeners.
	*
	* @param event the event
	* @return the event that was added
	*/
	@Deprecated
	public static bg.jug.workshop.liferay.cfp.model.Event addEvent(
		bg.jug.workshop.liferay.cfp.model.Event event) {
		return getService().addEvent(event);
	}

	public static void addTalkEvent(long talkId,
		bg.jug.workshop.liferay.cfp.model.Event event) {
		getService().addTalkEvent(talkId, event);
	}

	public static void addTalkEvent(long talkId, long eventId) {
		getService().addTalkEvent(talkId, eventId);
	}

	public static void addTalkEvents(long talkId,
		java.util.List<bg.jug.workshop.liferay.cfp.model.Event> events) {
		getService().addTalkEvents(talkId, events);
	}

	public static void addTalkEvents(long talkId, long[] eventIds) {
		getService().addTalkEvents(talkId, eventIds);
	}

	public static void clearTalkEvents(long talkId) {
		getService().clearTalkEvents(talkId);
	}

	public static int countGroupEvents(long companyId, long groupId) {
		return getService().countGroupEvents(companyId, groupId);
	}

	/**
	* Creates a new event with the primary key. Does not add the event to the database.
	*
	* @param eventId the primary key for the new event
	* @return the new event
	*/
	public static bg.jug.workshop.liferay.cfp.model.Event createEvent(
		long eventId) {
		return getService().createEvent(eventId);
	}

	/**
	* Deletes the event from the database. Also notifies the appropriate model listeners.
	*
	* @param event the event
	* @return the event that was removed
	*/
	@Deprecated
	public static bg.jug.workshop.liferay.cfp.model.Event deleteEvent(
		bg.jug.workshop.liferay.cfp.model.Event event) {
		return getService().deleteEvent(event);
	}

	/**
	* Deletes the event with the primary key from the database. Also notifies the appropriate model listeners.
	*
	* @param eventId the primary key of the event
	* @return the event that was removed
	* @throws PortalException if a event with the primary key could not be found
	*/
	@Deprecated
	public static bg.jug.workshop.liferay.cfp.model.Event deleteEvent(
		long eventId)
		throws com.liferay.portal.kernel.exception.PortalException {
		return getService().deleteEvent(eventId);
	}

	/**
	* Deletes given event and it's respective resource entity (if present).
	*
	* @param eventId the id of the event to delete
	* @param serviceContext the context of the service request (generated by the caller from servlet or portlet requests)
	* @throws PortalException if any error occur
	*/
	public static bg.jug.workshop.liferay.cfp.model.Event deleteEvent(
		long eventId,
		com.liferay.portal.kernel.service.ServiceContext serviceContext)
		throws com.liferay.portal.kernel.exception.PortalException {
		return getService().deleteEvent(eventId, serviceContext);
	}

	/**
	* @throws PortalException
	*/
	public static com.liferay.portal.kernel.model.PersistedModel deletePersistedModel(
		com.liferay.portal.kernel.model.PersistedModel persistedModel)
		throws com.liferay.portal.kernel.exception.PortalException {
		return getService().deletePersistedModel(persistedModel);
	}

	public static void deleteTalkEvent(long talkId,
		bg.jug.workshop.liferay.cfp.model.Event event) {
		getService().deleteTalkEvent(talkId, event);
	}

	public static void deleteTalkEvent(long talkId, long eventId) {
		getService().deleteTalkEvent(talkId, eventId);
	}

	public static void deleteTalkEvents(long talkId,
		java.util.List<bg.jug.workshop.liferay.cfp.model.Event> events) {
		getService().deleteTalkEvents(talkId, events);
	}

	public static void deleteTalkEvents(long talkId, long[] eventIds) {
		getService().deleteTalkEvents(talkId, eventIds);
	}

	public static com.liferay.portal.kernel.dao.orm.DynamicQuery dynamicQuery() {
		return getService().dynamicQuery();
	}

	/**
	* Performs a dynamic query on the database and returns the matching rows.
	*
	* @param dynamicQuery the dynamic query
	* @return the matching rows
	*/
	public static <T> java.util.List<T> dynamicQuery(
		com.liferay.portal.kernel.dao.orm.DynamicQuery dynamicQuery) {
		return getService().dynamicQuery(dynamicQuery);
	}

	/**
	* Performs a dynamic query on the database and returns a range of the matching rows.
	*
	* <p>
	* Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link bg.jug.workshop.liferay.cfp.model.impl.EventModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	* </p>
	*
	* @param dynamicQuery the dynamic query
	* @param start the lower bound of the range of model instances
	* @param end the upper bound of the range of model instances (not inclusive)
	* @return the range of matching rows
	*/
	public static <T> java.util.List<T> dynamicQuery(
		com.liferay.portal.kernel.dao.orm.DynamicQuery dynamicQuery, int start,
		int end) {
		return getService().dynamicQuery(dynamicQuery, start, end);
	}

	/**
	* Performs a dynamic query on the database and returns an ordered range of the matching rows.
	*
	* <p>
	* Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link bg.jug.workshop.liferay.cfp.model.impl.EventModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	* </p>
	*
	* @param dynamicQuery the dynamic query
	* @param start the lower bound of the range of model instances
	* @param end the upper bound of the range of model instances (not inclusive)
	* @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	* @return the ordered range of matching rows
	*/
	public static <T> java.util.List<T> dynamicQuery(
		com.liferay.portal.kernel.dao.orm.DynamicQuery dynamicQuery, int start,
		int end,
		com.liferay.portal.kernel.util.OrderByComparator<T> orderByComparator) {
		return getService()
				   .dynamicQuery(dynamicQuery, start, end, orderByComparator);
	}

	/**
	* Returns the number of rows matching the dynamic query.
	*
	* @param dynamicQuery the dynamic query
	* @return the number of rows matching the dynamic query
	*/
	public static long dynamicQueryCount(
		com.liferay.portal.kernel.dao.orm.DynamicQuery dynamicQuery) {
		return getService().dynamicQueryCount(dynamicQuery);
	}

	/**
	* Returns the number of rows matching the dynamic query.
	*
	* @param dynamicQuery the dynamic query
	* @param projection the projection to apply to the query
	* @return the number of rows matching the dynamic query
	*/
	public static long dynamicQueryCount(
		com.liferay.portal.kernel.dao.orm.DynamicQuery dynamicQuery,
		com.liferay.portal.kernel.dao.orm.Projection projection) {
		return getService().dynamicQueryCount(dynamicQuery, projection);
	}

	public static bg.jug.workshop.liferay.cfp.model.Event fetchEvent(
		long eventId) {
		return getService().fetchEvent(eventId);
	}

	/**
	* Returns the event matching the UUID and group.
	*
	* @param uuid the event's UUID
	* @param groupId the primary key of the group
	* @return the matching event, or <code>null</code> if a matching event could not be found
	*/
	public static bg.jug.workshop.liferay.cfp.model.Event fetchEventByUuidAndGroupId(
		java.lang.String uuid, long groupId) {
		return getService().fetchEventByUuidAndGroupId(uuid, groupId);
	}

	public static com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery getActionableDynamicQuery() {
		return getService().getActionableDynamicQuery();
	}

	/**
	* Returns the event with the primary key.
	*
	* @param eventId the primary key of the event
	* @return the event
	* @throws PortalException if a event with the primary key could not be found
	*/
	public static bg.jug.workshop.liferay.cfp.model.Event getEvent(long eventId)
		throws com.liferay.portal.kernel.exception.PortalException {
		return getService().getEvent(eventId);
	}

	/**
	* Returns the event matching the UUID and group.
	*
	* @param uuid the event's UUID
	* @param groupId the primary key of the group
	* @return the matching event
	* @throws PortalException if a matching event could not be found
	*/
	public static bg.jug.workshop.liferay.cfp.model.Event getEventByUuidAndGroupId(
		java.lang.String uuid, long groupId)
		throws com.liferay.portal.kernel.exception.PortalException {
		return getService().getEventByUuidAndGroupId(uuid, groupId);
	}

	/**
	* Returns a range of all the events.
	*
	* <p>
	* Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link bg.jug.workshop.liferay.cfp.model.impl.EventModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	* </p>
	*
	* @param start the lower bound of the range of events
	* @param end the upper bound of the range of events (not inclusive)
	* @return the range of events
	*/
	public static java.util.List<bg.jug.workshop.liferay.cfp.model.Event> getEvents(
		int start, int end) {
		return getService().getEvents(start, end);
	}

	/**
	* Returns all the events matching the UUID and company.
	*
	* @param uuid the UUID of the events
	* @param companyId the primary key of the company
	* @return the matching events, or an empty list if no matches were found
	*/
	public static java.util.List<bg.jug.workshop.liferay.cfp.model.Event> getEventsByUuidAndCompanyId(
		java.lang.String uuid, long companyId) {
		return getService().getEventsByUuidAndCompanyId(uuid, companyId);
	}

	/**
	* Returns a range of events matching the UUID and company.
	*
	* @param uuid the UUID of the events
	* @param companyId the primary key of the company
	* @param start the lower bound of the range of events
	* @param end the upper bound of the range of events (not inclusive)
	* @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	* @return the range of matching events, or an empty list if no matches were found
	*/
	public static java.util.List<bg.jug.workshop.liferay.cfp.model.Event> getEventsByUuidAndCompanyId(
		java.lang.String uuid, long companyId, int start, int end,
		com.liferay.portal.kernel.util.OrderByComparator<bg.jug.workshop.liferay.cfp.model.Event> orderByComparator) {
		return getService()
				   .getEventsByUuidAndCompanyId(uuid, companyId, start, end,
			orderByComparator);
	}

	/**
	* Returns the number of events.
	*
	* @return the number of events
	*/
	public static int getEventsCount() {
		return getService().getEventsCount();
	}

	public static com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery getExportActionableDynamicQuery(
		com.liferay.exportimport.kernel.lar.PortletDataContext portletDataContext) {
		return getService().getExportActionableDynamicQuery(portletDataContext);
	}

	/**
	* Returns a list of all events for given platform instance (company) and site (group)
	*
	* @param companyId the id of the portal instance (guarantees data sharding in multi-tenant environments)
	* @param groupId the id of the site (guarantees data sharding in multi-hosting environments)
	*/
	public static java.util.List<bg.jug.workshop.liferay.cfp.model.Event> getGroupEvents(
		long companyId, long groupId) {
		return getService().getGroupEvents(companyId, groupId);
	}

	/**
	* Returns a subset (page) of events for given platform instance (company) and site (group)
	*
	* @param companyId the id of the portal instance (guarantees data sharding in multi-tenant environments)
	* @param groupId the id of the site (guarantees data sharding in multi-hosting environments)
	* @param start the record to start from
	* @param end the record to end at
	*/
	public static java.util.List<bg.jug.workshop.liferay.cfp.model.Event> getGroupEvents(
		long companyId, long groupId, int start, int end) {
		return getService().getGroupEvents(companyId, groupId, start, end);
	}

	public static com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		return getService().getIndexableActionableDynamicQuery();
	}

	/**
	* Returns the OSGi service identifier.
	*
	* @return the OSGi service identifier
	*/
	public static java.lang.String getOSGiServiceIdentifier() {
		return getService().getOSGiServiceIdentifier();
	}

	public static com.liferay.portal.kernel.model.PersistedModel getPersistedModel(
		java.io.Serializable primaryKeyObj)
		throws com.liferay.portal.kernel.exception.PortalException {
		return getService().getPersistedModel(primaryKeyObj);
	}

	public static java.util.List<bg.jug.workshop.liferay.cfp.model.Event> getTalkEvents(
		long talkId) {
		return getService().getTalkEvents(talkId);
	}

	public static java.util.List<bg.jug.workshop.liferay.cfp.model.Event> getTalkEvents(
		long talkId, int start, int end) {
		return getService().getTalkEvents(talkId, start, end);
	}

	public static java.util.List<bg.jug.workshop.liferay.cfp.model.Event> getTalkEvents(
		long talkId, int start, int end,
		com.liferay.portal.kernel.util.OrderByComparator<bg.jug.workshop.liferay.cfp.model.Event> orderByComparator) {
		return getService().getTalkEvents(talkId, start, end, orderByComparator);
	}

	public static int getTalkEventsCount(long talkId) {
		return getService().getTalkEventsCount(talkId);
	}

	/**
	* Returns the talkIds of the talks associated with the event.
	*
	* @param eventId the eventId of the event
	* @return long[] the talkIds of talks associated with the event
	*/
	public static long[] getTalkPrimaryKeys(long eventId) {
		return getService().getTalkPrimaryKeys(eventId);
	}

	public static boolean hasTalkEvent(long talkId, long eventId) {
		return getService().hasTalkEvent(talkId, eventId);
	}

	public static boolean hasTalkEvents(long talkId) {
		return getService().hasTalkEvents(talkId);
	}

	/**
	* This method creates a new event or updates an existing one.
	* <p>
	* If there is {@code eventId} provided it updates the event with that id. Otherwise it creates a new event.
	* <p>
	* This method also creates/updates :
	* <ul>
	*     <li> respective {@link Resource} entity. This is needed to link the event with the resource framework
	* which among other things is used to manage resources' permissions
	* </ul>
	* <strong>NOTE: Important information for wrapping this method: </strong>
	* <ul>
	*     <li> it uses  {@code counterLocalService.increment(Event.class.getName())} as opposite to {@code counterLocalService.increment()}.
	* Take that into account to avoid id collisions if you modify the event creation process.
	* </ul>
	*
	* @param eventId the id of the event to save. If provided the it MUST be positive value.
	* @param name the event's name
	* @param eventDate the event'd date
	* @param venueId the venue's id
	* @param website the event's website
	* @param serviceContext the context of the service request (generated by the caller from servlet or portlet requests)
	* @throws IllegalArgumentException if {@code eventId} is provided but it is not a positive value
	* @throws NoSuchVenueException if {@code eventId} is provided but a event with such id can not be found
	* @throws PortalException if any error occur
	*/
	public static bg.jug.workshop.liferay.cfp.model.Event saveEvent(
		java.util.Optional<java.lang.Long> eventId, java.lang.String name,
		java.util.Date eventDate, java.util.Optional<java.lang.Long> venueId,
		java.lang.String website,
		com.liferay.portal.kernel.service.ServiceContext serviceContext)
		throws com.liferay.portal.kernel.exception.PortalException {
		return getService()
				   .saveEvent(eventId, name, eventDate, venueId, website,
			serviceContext);
	}

	public static void setTalkEvents(long talkId, long[] eventIds) {
		getService().setTalkEvents(talkId, eventIds);
	}

	/**
	* Updates the event in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	*
	* @param event the event
	* @return the event that was updated
	*/
	@Deprecated
	public static bg.jug.workshop.liferay.cfp.model.Event updateEvent(
		bg.jug.workshop.liferay.cfp.model.Event event) {
		return getService().updateEvent(event);
	}

	public static void updateTalks(long eventId,
		java.util.List<java.lang.Long> talks)
		throws com.liferay.portal.kernel.exception.PortalException {
		getService().updateTalks(eventId, talks);
	}

	public static EventLocalService getService() {
		return _serviceTracker.getService();
	}

	private static ServiceTracker<EventLocalService, EventLocalService> _serviceTracker =
		ServiceTrackerFactory.open(EventLocalService.class);
}