/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bg.jug.workshop.liferay.cfp.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Talk service. Represents a row in the &quot;CFP_Talk&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link bg.jug.workshop.liferay.cfp.model.impl.TalkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link bg.jug.workshop.liferay.cfp.model.impl.TalkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Talk
 * @see bg.jug.workshop.liferay.cfp.model.impl.TalkImpl
 * @see bg.jug.workshop.liferay.cfp.model.impl.TalkModelImpl
 * @generated
 */
@ProviderType
public interface TalkModel extends BaseModel<Talk>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a talk model instance should use the {@link Talk} interface instead.
	 */

	/**
	 * Returns the primary key of this talk.
	 *
	 * @return the primary key of this talk
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this talk.
	 *
	 * @param primaryKey the primary key of this talk
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this talk.
	 *
	 * @return the uuid of this talk
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this talk.
	 *
	 * @param uuid the uuid of this talk
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the company ID of this talk.
	 *
	 * @return the company ID of this talk
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this talk.
	 *
	 * @param companyId the company ID of this talk
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this talk.
	 *
	 * @return the group ID of this talk
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this talk.
	 *
	 * @param groupId the group ID of this talk
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this talk.
	 *
	 * @return the user ID of this talk
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this talk.
	 *
	 * @param userId the user ID of this talk
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this talk.
	 *
	 * @return the user uuid of this talk
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this talk.
	 *
	 * @param userUuid the user uuid of this talk
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this talk.
	 *
	 * @return the user name of this talk
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this talk.
	 *
	 * @param userName the user name of this talk
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this talk.
	 *
	 * @return the create date of this talk
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this talk.
	 *
	 * @param createDate the create date of this talk
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this talk.
	 *
	 * @return the modified date of this talk
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this talk.
	 *
	 * @param modifiedDate the modified date of this talk
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the talk ID of this talk.
	 *
	 * @return the talk ID of this talk
	 */
	public long getTalkId();

	/**
	 * Sets the talk ID of this talk.
	 *
	 * @param talkId the talk ID of this talk
	 */
	public void setTalkId(long talkId);

	/**
	 * Returns the title of this talk.
	 *
	 * @return the title of this talk
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this talk.
	 *
	 * @param title the title of this talk
	 */
	public void setTitle(String title);

	/**
	 * Returns the data of this talk.
	 *
	 * @return the data of this talk
	 */
	@AutoEscape
	public String getData();

	/**
	 * Sets the data of this talk.
	 *
	 * @param data the data of this talk
	 */
	public void setData(String data);

	/**
	 * Returns the structure ID of this talk.
	 *
	 * @return the structure ID of this talk
	 */
	public long getStructureId();

	/**
	 * Sets the structure ID of this talk.
	 *
	 * @param structureId the structure ID of this talk
	 */
	public void setStructureId(long structureId);

	/**
	 * Returns the template ID of this talk.
	 *
	 * @return the template ID of this talk
	 */
	public long getTemplateId();

	/**
	 * Sets the template ID of this talk.
	 *
	 * @param templateId the template ID of this talk
	 */
	public void setTemplateId(long templateId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Talk talk);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Talk> toCacheModel();

	@Override
	public Talk toEscapedModel();

	@Override
	public Talk toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}