/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package bg.jug.workshop.liferay.cfp.model.impl;

import aQute.bnd.annotation.ProviderType;

import bg.jug.workshop.liferay.cfp.model.Talk;
import bg.jug.workshop.liferay.cfp.model.TalkModel;
import bg.jug.workshop.liferay.cfp.model.TalkSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Talk service. Represents a row in the &quot;CFP_Talk&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TalkModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TalkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TalkImpl
 * @see Talk
 * @see TalkModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TalkModelImpl extends BaseModelImpl<Talk> implements TalkModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a talk model instance should use the {@link Talk} interface instead.
	 */
	public static final String TABLE_NAME = "CFP_Talk";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "talkId", Types.BIGINT },
			{ "title", Types.VARCHAR },
			{ "data_", Types.CLOB },
			{ "structureId", Types.BIGINT },
			{ "templateId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("talkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("data_", Types.CLOB);
		TABLE_COLUMNS_MAP.put("structureId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("templateId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table CFP_Talk (uuid_ VARCHAR(75) null,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,talkId LONG not null primary key,title VARCHAR(200) null,data_ TEXT null,structureId LONG,templateId LONG)";
	public static final String TABLE_SQL_DROP = "drop table CFP_Talk";
	public static final String ORDER_BY_JPQL = " ORDER BY talk.talkId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CFP_Talk.talkId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(bg.jug.workshop.liferay.cfp.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.bg.jug.workshop.liferay.cfp.model.Talk"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(bg.jug.workshop.liferay.cfp.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.bg.jug.workshop.liferay.cfp.model.Talk"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(bg.jug.workshop.liferay.cfp.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.bg.jug.workshop.liferay.cfp.model.Talk"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long UUID_COLUMN_BITMASK = 4L;
	public static final long TALKID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Talk toModel(TalkSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Talk model = new TalkImpl();

		model.setUuid(soapModel.getUuid());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTalkId(soapModel.getTalkId());
		model.setTitle(soapModel.getTitle());
		model.setData(soapModel.getData());
		model.setStructureId(soapModel.getStructureId());
		model.setTemplateId(soapModel.getTemplateId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Talk> toModels(TalkSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Talk> models = new ArrayList<Talk>(soapModels.length);

		for (TalkSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final String MAPPING_TABLE_CFP_TALK_EVENT_NAME = "CFP_Talk_Event";
	public static final Object[][] MAPPING_TABLE_CFP_TALK_EVENT_COLUMNS = {
			{ "companyId", Types.BIGINT },
			{ "eventId", Types.BIGINT },
			{ "talkId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_CFP_TALK_EVENT_SQL_CREATE = "create table CFP_Talk_Event (companyId LONG not null,eventId LONG not null,talkId LONG not null,primary key (eventId, talkId))";
	public static final boolean FINDER_CACHE_ENABLED_CFP_TALK_EVENT = GetterUtil.getBoolean(bg.jug.workshop.liferay.cfp.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.CFP_Talk_Event"), true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(bg.jug.workshop.liferay.cfp.service.util.ServiceProps.get(
				"lock.expiration.time.bg.jug.workshop.liferay.cfp.model.Talk"));

	public TalkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _talkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTalkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _talkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Talk.class;
	}

	@Override
	public String getModelClassName() {
		return Talk.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("talkId", getTalkId());
		attributes.put("title", getTitle());
		attributes.put("data", getData());
		attributes.put("structureId", getStructureId());
		attributes.put("templateId", getTemplateId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long talkId = (Long)attributes.get("talkId");

		if (talkId != null) {
			setTalkId(talkId);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String data = (String)attributes.get("data");

		if (data != null) {
			setData(data);
		}

		Long structureId = (Long)attributes.get("structureId");

		if (structureId != null) {
			setStructureId(structureId);
		}

		Long templateId = (Long)attributes.get("templateId");

		if (templateId != null) {
			setTemplateId(templateId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getTalkId() {
		return _talkId;
	}

	@Override
	public void setTalkId(long talkId) {
		_talkId = talkId;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@JSON
	@Override
	public String getData() {
		if (_data == null) {
			return StringPool.BLANK;
		}
		else {
			return _data;
		}
	}

	@Override
	public void setData(String data) {
		_data = data;
	}

	@JSON
	@Override
	public long getStructureId() {
		return _structureId;
	}

	@Override
	public void setStructureId(long structureId) {
		_structureId = structureId;
	}

	@JSON
	@Override
	public long getTemplateId() {
		return _templateId;
	}

	@Override
	public void setTemplateId(long templateId) {
		_templateId = templateId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Talk.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Talk.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Talk toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Talk)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TalkImpl talkImpl = new TalkImpl();

		talkImpl.setUuid(getUuid());
		talkImpl.setCompanyId(getCompanyId());
		talkImpl.setGroupId(getGroupId());
		talkImpl.setUserId(getUserId());
		talkImpl.setUserName(getUserName());
		talkImpl.setCreateDate(getCreateDate());
		talkImpl.setModifiedDate(getModifiedDate());
		talkImpl.setTalkId(getTalkId());
		talkImpl.setTitle(getTitle());
		talkImpl.setData(getData());
		talkImpl.setStructureId(getStructureId());
		talkImpl.setTemplateId(getTemplateId());

		talkImpl.resetOriginalValues();

		return talkImpl;
	}

	@Override
	public int compareTo(Talk talk) {
		long primaryKey = talk.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Talk)) {
			return false;
		}

		Talk talk = (Talk)obj;

		long primaryKey = talk.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TalkModelImpl talkModelImpl = this;

		talkModelImpl._originalUuid = talkModelImpl._uuid;

		talkModelImpl._originalCompanyId = talkModelImpl._companyId;

		talkModelImpl._setOriginalCompanyId = false;

		talkModelImpl._originalGroupId = talkModelImpl._groupId;

		talkModelImpl._setOriginalGroupId = false;

		talkModelImpl._setModifiedDate = false;

		talkModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Talk> toCacheModel() {
		TalkCacheModel talkCacheModel = new TalkCacheModel();

		talkCacheModel.uuid = getUuid();

		String uuid = talkCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			talkCacheModel.uuid = null;
		}

		talkCacheModel.companyId = getCompanyId();

		talkCacheModel.groupId = getGroupId();

		talkCacheModel.userId = getUserId();

		talkCacheModel.userName = getUserName();

		String userName = talkCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			talkCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			talkCacheModel.createDate = createDate.getTime();
		}
		else {
			talkCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			talkCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			talkCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		talkCacheModel.talkId = getTalkId();

		talkCacheModel.title = getTitle();

		String title = talkCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			talkCacheModel.title = null;
		}

		talkCacheModel.data = getData();

		String data = talkCacheModel.data;

		if ((data != null) && (data.length() == 0)) {
			talkCacheModel.data = null;
		}

		talkCacheModel.structureId = getStructureId();

		talkCacheModel.templateId = getTemplateId();

		return talkCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", talkId=");
		sb.append(getTalkId());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", data=");
		sb.append(getData());
		sb.append(", structureId=");
		sb.append(getStructureId());
		sb.append(", templateId=");
		sb.append(getTemplateId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("bg.jug.workshop.liferay.cfp.model.Talk");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>talkId</column-name><column-value><![CDATA[");
		sb.append(getTalkId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data</column-name><column-value><![CDATA[");
		sb.append(getData());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>structureId</column-name><column-value><![CDATA[");
		sb.append(getStructureId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>templateId</column-name><column-value><![CDATA[");
		sb.append(getTemplateId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Talk.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Talk.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _talkId;
	private String _title;
	private String _data;
	private long _structureId;
	private long _templateId;
	private long _columnBitmask;
	private Talk _escapedModel;
}